name: Plonktam ci

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the current tag from the repository
        id: get_tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Increment the tag
        id: increment_tag
        # run: echo ::set-output name=tag::$(python3 versioning.py ${{ steps.get_tag.outputs.tag }})
        run: |
            current_tag="${{ steps.get_tag.outputs.tag }}"
            new_version=$(python3 versioning.py "$current_tag")
            echo "::set-output name=tag::$new_version"
      - name: Debug - Print Incremented Tag
        run: echo ${{ steps.increment_tag.outputs.tag }}

      -  name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_TOKEN }}
     
      -  name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
         
      -  name: Build and push
         uses: docker/build-push-action@v4
         with:
           context: .
           file: ./Dockerfile
           build-args: |
            REQUIREMENTS_FILE=./requirements.txt 
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/plonktam:${{ steps.increment_tag.outputs.tag }}
